### ISSUE TITLE
trailing clear icon if i send null not hide it

### ISSUE THREAD

**Issue by varindergroove** [mdikcinar/searchable_dropdown#13]
I went to trailing clear icon control its my hand, if i send null widget in trailing clear icon please remove it no use clear functionality. please do this.

**Comment by mdikcinar** [comment]
These are two ways to do this, you can pass a SizedBox() to trailingClearIcon or i can add a showClearIcon boolean parametter to do that. Because if you pass null, it will use the default clear icon. You must pass an empty widget if you want to don't show anything there.

**Comment by varindergroove** [comment]
ok , but i went to show always trailing icon like dropdown functionality not use trailingClearIcon functionality

**Comment by mdikcinar** [comment]
Okey than i will handle this.

**Comment by mdikcinar** [comment]
https://github.com/mdikcinar/searchable_dropdown/tree/feature/optional_clear_icon
Can you try it with this branch. I added a hasTrailingClearIcon parametter. Waiting your feedback to publish this version.

pubspec.yaml example for branch
```
 searchable_paginated_dropdown:
    git:
      url: git@github.com:mdikcinar/searchable_dropdown.git
      ref: feature/optional_clear_icon
```
